/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pequeña_Aplicacion;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class GestionDeAlmacen extends javax.swing.JFrame {
    static Connection con;
    static Statement st;
    static PreparedStatement pstSel;
    static PreparedStatement pstInse;

    
    /**
     * Creates new form GestionDeAlmacen
     */
    public GestionDeAlmacen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Almacenes");

        jMenu1.setMnemonic('m');
        jMenu1.setText("Mantenimiento");

        jMenuItem1.setMnemonic('c');
        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setMnemonic('p');
        jMenuItem2.setText("Proveedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setMnemonic('a');
        jMenuItem3.setText("Articulos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('a');
        jMenu2.setText("Almacén");

        jMenuItem4.setMnemonic('p');
        jMenuItem4.setText("Pedidos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Clientes v=new Clientes(this);
            setEnabled(false);
            setVisible(false);
            v.setVisible(true);
            
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Proveedores v=new Proveedores(this);
            setEnabled(false);
            setVisible(false);
            v.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Articulos v=new Articulos(this);
            setEnabled(false);
            setVisible(false);
            v.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Pedidos v=new Pedidos(this);
            setEnabled(false);
            setVisible(false);
            v.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    public static boolean existe (String or, String tabla) throws SQLException{
        String orden="SELECT * FROM "+tabla+" WHERE codigo=?";
        ResultSet rs = null;
        try {
            pstInse=con.prepareStatement(orden);
            pstInse.setString(1, or);
            rs=pstInse.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(GestionDeAlmacen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return rs.next();
    } 

    public static ResultSet mostrar (String or, String tabla) throws SQLException{
        String orden="SELECT * FROM "+tabla+" WHERE codigo=?";
        if (tabla.equals("Pedidos")) {
            orden="SELECT * FROM "+tabla+" WHERE codigoC=?";
        }
        ResultSet rs = null;
            pstInse=con.prepareStatement(orden);
            pstInse.setString(1, or);
            rs=pstInse.executeQuery();
            rs.next();
        return rs;
    }
    public static void bajas (String or, String tabla) throws SQLException{
        String orden="DELETE FROM "+tabla+" WHERE codigo=?";
            pstInse=con.prepareStatement(orden);
            pstInse.setString(1, or);
            pstInse.executeUpdate();
        
       
     
    } 
    public static ResultSet mostrarEspec(String orden) throws SQLException {
        pstInse = con.prepareStatement(orden);
        ResultSet rs = pstInse.executeQuery();
            return rs;
    }
    public static void altas (ArrayList<String> al, String tabla) throws SQLException{
        String orden="INSERT INTO "+tabla+" VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
            pstInse=con.prepareStatement(orden);
            pstInse.setString(1, al.get(0));
            pstInse.setString(2, al.get(1));
            pstInse.setString(3, al.get(2));
            pstInse.setString(4, al.get(3));
            pstInse.setString(5, al.get(4));
            pstInse.setString(6, al.get(5));
            pstInse.setString(7, al.get(6));
            pstInse.setString(8, al.get(7));
            pstInse.setString(9, al.get(8));
            pstInse.setString(10, al.get(9));
            pstInse.setString(11, al.get(10));
            pstInse.setString(12, al.get(11));
            pstInse.executeUpdate();       
    } 
        public static void altas2 (ArrayList<String> al, String tabla) throws SQLException{
        String orden="INSERT INTO "+tabla+" VALUES (?,?,?,?,?,?)";
            pstInse=con.prepareStatement(orden);
            pstInse.setString(1, al.get(0));
            pstInse.setString(2, al.get(1));
            pstInse.setString(3, al.get(2));
            pstInse.setString(4, al.get(3));
            pstInse.setString(5, al.get(4));
            pstInse.setString(6, al.get(5));
            pstInse.executeUpdate();       
    } 
        public static void altas3 (ArrayList<String> al, String tabla) throws SQLException{
        String orden="INSERT INTO "+tabla+" VALUES (?,?,?,?,?)";
            pstInse=con.prepareStatement(orden);
            pstInse.setString(1, al.get(0));
            pstInse.setString(2, al.get(1));
            pstInse.setString(3, al.get(2));
            pstInse.setString(4, al.get(3));
            pstInse.setString(5, al.get(4));
            pstInse.executeUpdate();       
    } 
    public static void modificaciones (String or, String actual, String cod, String tabla) throws SQLException{
            String orden="UPDATE "+tabla+" SET "+or+" = ? where codigo=?";

            pstInse=con.prepareStatement(orden);
            pstInse.setString(1, actual);
            pstInse.setString(2, cod);
            pstInse.executeUpdate();

    } 
    public static void comienzoTransac () throws SQLException {
           con.setAutoCommit(false);
    } 
    public static void confirmTransac () throws SQLException {
           con.commit();
    } 
    public static void deshacerTransac () throws SQLException {
           con.rollback();
    } 
    public static void finTransac () throws SQLException {
           con.setAutoCommit(true);
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            try {
                Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            } catch (ClassNotFoundException e1) {
                Logger.getLogger(GestionDeAlmacen.class.getName()).log(Level.SEVERE, null, e1);
            }
                String rutaBBDD="./src/Practica_Evaluable2/bbddPracticaEv2";
                String cadenaConexion = "jdbc:derby:" + rutaBBDD + ";create=true";
            try {
                con = DriverManager.getConnection(cadenaConexion);
            } catch (SQLException e) {
                Logger.getLogger(GestionDeAlmacen.class.getName()).log(Level.SEVERE, null, e);
            }
        try {
            st=con.createStatement();
        } catch (Exception e) {
        }
               
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDeAlmacen().setVisible(true);
            }
        });
        // Comprobar que existe el driver Derby en nuestro proyecto Eclipse


    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
