/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pequeña_Aplicacion;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class Pedidos extends javax.swing.JFrame {
    static javax.swing.JFrame padre;
    private int aux=0;
    /**
     * Creates new form Pedidos
     */
    public Pedidos(javax.swing.JFrame padre) {
        Pedidos.padre = padre;
        enableEvents(java.awt.AWTEvent.WINDOW_EVENT_MASK);
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        acep = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        factu = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        canTod = new javax.swing.JButton();
        canPed = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField13.setEnabled(false);
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField13KeyPressed(evt);
            }
        });

        jTextField2.setEnabled(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("N.I.F.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Código");

        acep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        acep.setMnemonic('A');
        acep.setText("Aceptar");
        acep.setEnabled(false);
        acep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acepActionPerformed(evt);
            }
        });

        jTextField3.setEnabled(false);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        factu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        factu.setMnemonic('f');
        factu.setText("Factuura");
        factu.setEnabled(false);
        factu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factuActionPerformed(evt);
            }
        });

        jTextField4.setEnabled(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Apellidos");

        jTextField6.setEnabled(false);
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Domicilio");

        jTextField7.setEnabled(false);
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("C.P.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jTextField5.setEnabled(false);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salir.setMnemonic('s');
        salir.setText("Salir");
        salir.setEnabled(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jTextField8.setEnabled(false);
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Localidad");

        canTod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canTod.setMnemonic('c');
        canTod.setText("Cancelar Todo");
        canTod.setEnabled(false);
        canTod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canTodActionPerformed(evt);
            }
        });

        canPed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canPed.setMnemonic('p');
        canPed.setText("Cancelar Pedido");
        canPed.setEnabled(false);
        canPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canPedActionPerformed(evt);
            }
        });

        jTextField9.setEnabled(false);
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });

        jTextField10.setEnabled(false);
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Descripción");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Articulo");

        jTextField11.setEnabled(false);
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Unidades");

        jTextField12.setEnabled(false);
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Stock");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Precio  ");

        jTextField14.setEnabled(false);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField14KeyPressed(evt);
            }
        });

        jTextField15.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Importe");

        jMenu1.setMnemonic('p');
        jMenu1.setText("Pedidos");

        jMenuItem1.setMnemonic('c');
        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setMnemonic('p');
        jMenuItem2.setText("Proveedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setMnemonic('v');
        jMenuItem3.setText("Volver");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel11)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(canPed, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(canTod, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(factu)
                        .addGap(10, 10, 10)
                        .addComponent(acep)
                        .addGap(9, 9, 9)
                        .addComponent(salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(0, 307, Short.MAX_VALUE))
                                .addComponent(jTextField10)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(factu)
                    .addComponent(acep)
                    .addComponent(salir))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(canPed))
                    .addComponent(canTod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(255, 255, 255)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8))
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel10)
                    .addGap(1, 1, 1)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
                if (jTextField1.getText().length()!=5) {
                    JOptionPane.showConfirmDialog(this,"El Código debe tener 5 caracteres.", "Gestión de clientes", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        switch(aux){
                            case 0:
                                if (GestionDeAlmacen.existe(jTextField1.getText(),"Clientes")) {
                                    /*codigo para mostrar*/
                                    ResultSet rs=GestionDeAlmacen.mostrar(jTextField1.getText(),"Clientes");
                                    String div=rs.getString("nif");
                                    String divNum=div.substring(0,8);
                                    String divLet=div.substring(8);
                                    jTextField2.setText(divNum);
                                    jTextField3.setText(divLet);
                                    jTextField5.setText(rs.getString("apellidos"));
                                    jTextField4.setText(rs.getString("nombre"));
                                    jTextField6.setText(rs.getString("domicilio"));
                                    jTextField7.setText(rs.getString("cp"));
                                    jTextField8.setText(rs.getString("loaclidad"));
                                    jTextField13.setText(rs.getString("total_ventas"));
                                    jTextField1.setEnabled(false);
                                    jTextField14.setEnabled(true);
                                    jTextField14.grabFocus();
                                    canTod.setEnabled(true);
                                } else {
                                    JOptionPane.showConfirmDialog(this,"Código Erróneo", "Código no existente. Imposible dar de baja este código.", JOptionPane.ERROR_MESSAGE);
                                }
                            break;
                            case 1:
                                if (GestionDeAlmacen.existe(jTextField1.getText(),"Proveedores")) {
                                /*codigo para mostrar*/
                                ResultSet rs=GestionDeAlmacen.mostrar(jTextField1.getText(),"Proveedores");
                                String div=rs.getString("nif");
                                String divNum=div.substring(0,8);
                                String divLet=div.substring(8);
                                jTextField2.setText(divNum);
                                jTextField3.setText(divLet);
                                jTextField5.setText(rs.getString("apellidos"));
                                jTextField4.setText(rs.getString("nombre"));
                                jTextField6.setText(rs.getString("domicilio"));
                                jTextField7.setText(rs.getString("cp"));
                                jTextField8.setText(rs.getString("loaclidad"));
                                jTextField13.setText(rs.getString("total_compras"));
                                jTextField1.setEnabled(false);
                                jTextField14.setEnabled(true);
                                jTextField14.grabFocus();
                                canTod.setEnabled(true);
                            } else {
                                JOptionPane.showConfirmDialog(this,"Código Erróneo", "Código no existente. Imposible dar de baja este código.", JOptionPane.ERROR_MESSAGE);
                            }
                                
                                break;
                                default:
                                    JOptionPane.showConfirmDialog(this,"Gestión de pedidos", "Error fatal, por favor llame al tecnico.", JOptionPane.ERROR_MESSAGE);
                                    break;
                    }
                    } catch (SQLException ex) {
                        Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2KeyPressed

    private void acepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acepActionPerformed
        try {
            // TODO add your handling code here:
            
            if (aux==0) {
                //insertamos en la tabla pedidos.
                ArrayList <String> al=new ArrayList <String>();
                al.add(jTextField1.getText());
                al.add(null);
                al.add(jTextField14.getText());
                al.add(jTextField9.getText());
                Date d=new Date();
                SimpleDateFormat  myFormatObj = new SimpleDateFormat("dd-MM-yyyy");
                String fecha = myFormatObj.format(d.getTime());
                al.add(fecha);
                GestionDeAlmacen.altas3(al, "Pedidos");
                
                //ahora hacemos el update de la tabla Articulos.
                float res=Float.valueOf(jTextField12.getText())-Float.valueOf(jTextField9.getText());
                String resL=String.valueOf(res);
                GestionDeAlmacen.modificaciones("stock", resL, jTextField14.getText(), "Articulos");
                //ahora hacemos el update de la tabla Clientes.
                float res2=Float.valueOf(jTextField11.getText())*Float.valueOf(jTextField9.getText());
                ResultSet rs2=GestionDeAlmacen.mostrar(jTextField1.getText(), "Clientes");
                float resfinal=res2+Float.valueOf(rs2.getString("total_ventas"));
                String resL2=String.valueOf(resfinal);
                GestionDeAlmacen.modificaciones("total_ventas", resL2, jTextField1.getText(), "Clientes");
                
                ResultSet rs=GestionDeAlmacen.mostrar(jTextField1.getText(), "Clientes");
                    jTextField13.setText(rs.getString("total_ventas"));
                
            } else {
                if (aux==1) {
                    ArrayList <String> al=new ArrayList <String>();
                    al.add(null);
                    al.add(jTextField1.getText());
                    al.add(jTextField14.getText());
                    al.add(jTextField9.getText());
                    Date d=new Date();
                    SimpleDateFormat  myFormatObj = new SimpleDateFormat("dd-MM-yyyy");
                    String fecha = myFormatObj.format(d.getTime());
                    al.add(fecha);
                    GestionDeAlmacen.altas3(al, "Pedidos");
                    //ahora hacemos el update de la tabla Articulos.
                    float res=Float.valueOf(jTextField12.getText())+Float.valueOf(jTextField9.getText());
                    String resL=String.valueOf(res);
                    GestionDeAlmacen.modificaciones("stock", resL, jTextField14.getText(), "Articulos");
                    //ahora hacemos el update de la tabla Proveedores.
                    
                    float res2=Float.valueOf(jTextField11.getText())*Float.valueOf(jTextField9.getText());
                    ResultSet rs2=GestionDeAlmacen.mostrar(jTextField1.getText(), "Clientes");
                    float resfinal=res2+Float.valueOf(rs2.getString("total_ventas"));
                    String resL2=String.valueOf(resfinal);
                    GestionDeAlmacen.modificaciones("total_compras", resL2, jTextField1.getText(), "Proveedores");
                    
                    ResultSet rs=GestionDeAlmacen.mostrar(jTextField1.getText(), "Proveedores");
                    jTextField13.setText(rs.getString("total_compras"));
                    }
            }
            factu.setEnabled(true);
            acep.setEnabled(false);
            canPed.setEnabled(false);
            actDesCasillas(1);
        } catch (SQLException ex) {
            
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_acepActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField4.grabFocus();
    }//GEN-LAST:event_jTextField3KeyPressed

    private void factuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factuActionPerformed
        if (aux==0) {
            try{
            ResultSet rs=GestionDeAlmacen.mostrar(jTextField1.getText(), "Clientes");
            
            File f=new File("./src/Practica_Evaluable2/NumeroFactura");
            BufferedReader br=new BufferedReader(new FileReader(f));
            int numF=Integer.valueOf(br.readLine());
            br.close();
            PrintWriter pw=new PrintWriter(new FileWriter(f));
            String numF2=String.valueOf(numF+1);
            pw.write(numF2);
            pw.close();
            Date d=new Date();
            SimpleDateFormat  myFormatObj = new SimpleDateFormat("dd-MM-yyyy");
            String fecha = myFormatObj.format(d.getTime());
            String fact="Empresa Inventada De Almacenes S.A.                N.I.F.: 84629517D\n" +
                        "Fecha:"+fecha+"                                                      Factura nº:"+numF+"\n" +
                        "Cliente:"+rs.getString("codigo")+"                                                       N.I.F.:"+rs.getString("nif")+"\n" +
                        "Nombre:"+rs.getString("nombre")+" "+rs.getString("apellidos")+"\n" +
                        "           Artículo      Unidades       Precio      Importe\n"+
                        "           ¯¯¯¯¯¯      ¯¯¯¯¯¯¯       ¯¯¯¯¯      ¯¯¯¯¯¯¯\n";
            
            ResultSet rs3=GestionDeAlmacen.mostrar(jTextField1.getText(), "Pedidos");
            float imptotal=0;
                do{
                    ResultSet rs2=GestionDeAlmacen.mostrar(rs3.getString("codigoA"), "Articulos");
                    float imp=Float.valueOf(rs2.getString("precio_venta"))*Float.valueOf(rs3.getString("unidades"));
                    imptotal=imptotal+imp;
                    fact=fact+"           "+rs3.getString("codigoA")+"        "+rs3.getString("unidades")+"                  "+rs2.getString("precio_venta")+"            "+imp+"\n";
                }while(rs3.next());
            fact=fact+"\n                                             Total factura (I.V.A. inc.):"+imptotal;
            
            JOptionPane.showMessageDialog(this, fact, "Factura", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e){
            
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
            }                      
        } 
        actDesCasillas(2); 
        try {
            GestionDeAlmacen.confirmTransac();
            GestionDeAlmacen.finTransac();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_factuActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField5.grabFocus();
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField7.grabFocus();
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField8.grabFocus();
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField6.grabFocus();
    }//GEN-LAST:event_jTextField5KeyPressed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        actDesCasillas(2); 
        try {
            GestionDeAlmacen.deshacerTransac();
            GestionDeAlmacen.finTransac();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salirActionPerformed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyPressed

    private void canTodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canTodActionPerformed
        // TODO add your handling code here:
        actDesCasillas(2);
        jTextField1.setEnabled(true);
        salir.setEnabled(true);
        try {
            GestionDeAlmacen.deshacerTransac();
            GestionDeAlmacen.finTransac();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_canTodActionPerformed

    private void canPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canPedActionPerformed
        // TODO add your handling code here:
        actDesCasillas(1);        
    }//GEN-LAST:event_canPedActionPerformed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            if (jTextField9.getText().matches("[0-9]+") && !jTextField9.getText().equals("0")) {
                if (aux==0) {
                    if ((float) Integer.valueOf(jTextField9.getText())<=Float.valueOf(jTextField12.getText()) && ((float) Integer.valueOf(jTextField9.getText()))>0 ) {
                    jTextField9.setEnabled(false);
                    acep.setEnabled(true);
                    String importe=String.valueOf(Float.valueOf(jTextField11.getText())*Float.valueOf(jTextField9.getText()));
                    jTextField15.setText(importe);
                } else {
                    JOptionPane.showConfirmDialog(this,"Las unidades pedidas no pueden superar la cantidad de articulos en stock.", "Gestión de pedidos", JOptionPane.ERROR_MESSAGE);
                }
                }else {
                if (((float) Integer.valueOf(jTextField9.getText()))<0) {
                    JOptionPane.showConfirmDialog(this,"Las unidades pedidas no pueden superar la cantidad de articulos en stock.", "Gestión de pedidos", JOptionPane.ERROR_MESSAGE);
                 } else {
                    jTextField9.setEnabled(false);
                    acep.setEnabled(true);
                    String importe=String.valueOf(Float.valueOf(jTextField11.getText())*Float.valueOf(jTextField9.getText()));
                    jTextField15.setText(importe);
                }
                }
                
            } else {
                JOptionPane.showConfirmDialog(this,"El campo Unidades no puede estar vacio, debe ser una nñumero y no puede tener el valor 0.", "Gestión de pedidos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10){
            jTextField4.grabFocus();
        }
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField5.grabFocus();
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12KeyPressed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode()==10) {
                if (jTextField14.getText().length()!=5) {
                    JOptionPane.showConfirmDialog(this,"El código del articulo debe tener 5 caracteres.", "Gestión de pedidos", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        if (GestionDeAlmacen.existe(jTextField14.getText(),"Articulos")) {
                            /*codigo para mostrar*/
                            ResultSet rs=GestionDeAlmacen.mostrar(jTextField14.getText(),"Articulos");
                            jTextField10.setText(rs.getString("descripción"));
                            jTextField12.setText(rs.getString("stock"));
                            if (aux==0) {
                               jTextField11.setText(rs.getString("precio_venta")); 
                            }
                            if (aux==1) {
                                jTextField11.setText(rs.getString("precio_compra"));
                            }
                            jTextField14.setEnabled(false);
                            jTextField9.setEnabled(true);
                            jTextField9.grabFocus();
                            canPed.setEnabled(true);
                        } else {
                            JOptionPane.showConfirmDialog(this,"Código Erróneo", "Código no existente. Imposible dar de baja este código.", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            
        }
        
    }//GEN-LAST:event_jTextField14KeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        actDesCasillas(2);
        aux=0;
        salir.setEnabled(true);
        jTextField1.setEnabled(true);
        jTextField1.grabFocus();
        factu.setText("Factura");
        try {
            GestionDeAlmacen.comienzoTransac();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        actDesCasillas(2);
        aux=1; 
        salir.setEnabled(true);
        factu.setText("Finalizar");
        jTextField1.setEnabled(true);
        jTextField1.grabFocus();
        try {
            GestionDeAlmacen.comienzoTransac();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        padre.setEnabled(true);
        padre.setVisible(true);
        try {
            GestionDeAlmacen.finTransac();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos(padre).setVisible(true);
            }
        });
    }
    protected void processWindowEvent(java.awt.event.WindowEvent e) {/*Este metodo debemos añadirlo completo a mano,
     con el habilitamos de nuevo la primera ventana.*/
        super.processWindowEvent(e);
        if (e.getID() == java.awt.event.WindowEvent.WINDOW_CLOSING) {
        padre.setEnabled(true);
        padre.setVisible(true); 
        try {
            GestionDeAlmacen.finTransac();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }
    private void actDesCasillas(int i) {
       switch(i)
            {
                case 1:
                    jTextField9.setText("");
                    jTextField10.setText("");
                    jTextField11.setText("");
                    jTextField12.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                    jTextField1.setEnabled(false);
                    jTextField14.setEnabled(true);
                    jTextField14.grabFocus();
                    jTextField9.setEnabled(false);
                    acep.setEnabled(false);
                    canPed.setEnabled(false);
                    break;
                case 2:
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    jTextField10.setText("");
                    jTextField11.setText("");
                    jTextField12.setText("");
                    jTextField13.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                    jTextField1.setEnabled(false);
                    jTextField9.setEnabled(false);
                    jTextField14.setEnabled(false);
                    salir.setEnabled(false);
                    acep.setEnabled(false);
                    factu.setEnabled(false);
                    canPed.setEnabled(false);
                    canTod.setEnabled(false);
                    break;
                default:
                    
            }
        
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acep;
    private javax.swing.JButton canPed;
    private javax.swing.JButton canTod;
    private javax.swing.JButton factu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
