/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pequeña_Aplicacion;

import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author doort
 */
public class Proveedores extends javax.swing.JFrame {
    static javax.swing.JFrame padre;
    int aux=1;

    /**
     * Creates new form Altas2
     */
    public Proveedores(javax.swing.JFrame padre) {
        Proveedores.padre = padre;
        enableEvents(java.awt.AWTEvent.WINDOW_EVENT_MASK);
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jScrollPane2.setVisible(false);
        this.setBounds(0, 0, 487, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Almacenes - Proveedores");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("e-mail");

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField13.setEnabled(false);
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField13KeyPressed(evt);
            }
        });

        jTextField2.setEnabled(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("N.F.I.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total Compras");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setMnemonic('A');
        jButton1.setText("Aceptar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setEnabled(false);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setMnemonic('C');
        jButton2.setText("Cancelar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField4.setEnabled(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Apellidos");

        jTextField6.setEnabled(false);
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Domicilio");

        jTextField7.setEnabled(false);
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("C.P.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jTextField5.setEnabled(false);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setMnemonic('s');
        jButton3.setText("Salir");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField8.setEnabled(false);
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Localidad");

        jTextField9.setToolTipText("");
        jTextField9.setEnabled(false);
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Teléfono");

        jTextField10.setEnabled(false);
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Móvil");

        jTextField11.setEnabled(false);
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Fax");

        jTextField12.setEnabled(false);
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Código");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        jMenu1.setMnemonic('m');
        jMenu1.setText("Mantenimiento");

        jMenuItem1.setMnemonic('a');
        jMenuItem1.setText("Altas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setMnemonic('b');
        jMenuItem2.setText("Bajas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setMnemonic('m');
        jMenuItem3.setText("Modificaciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setMnemonic('v');
        jMenuItem4.setText("Volver");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('c');
        jMenu2.setText("Consultas");

        jMenu3.setMnemonic('p');
        jMenu3.setText("Por Código");

        jMenuItem7.setMnemonic('c');
        jMenuItem7.setText("Por código");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setMnemonic('e');
        jMenuItem8.setText("Entre código");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenu2.add(jMenu3);

        jMenuItem5.setMnemonic('a');
        jMenuItem5.setText("Por Apellido");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setMnemonic('g');
        jMenuItem6.setText("Por Gráfico");
        jMenuItem6.setToolTipText("");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem9.setMnemonic('c');
        jMenuItem9.setText("Por Código");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(345, 345, 345)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(159, 159, 159))
                                        .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(69, 69, 69)
                                    .addComponent(jLabel9))
                                .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(jButton3))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            switch(aux)
            {
                case 1:
                if (jTextField1.getText().length()!=5) {
                    JOptionPane.showConfirmDialog(this,"El Código debe tener 5 caracteres.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                } else {
                try {
                    if (GestionDeAlmacen.existe(jTextField1.getText(),"Proveedores")) {
                        JOptionPane.showConfirmDialog(this, "Código ya existente. Imposible dar de alta este código.", "Código Erróneo", JOptionPane.ERROR_MESSAGE);
                    } else {
                        actDesCasillas(1);
                        jTextField13.setText("00.00");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
                    break;
                case 2:
                if (jTextField1.getText().length()!=5) {
                    JOptionPane.showConfirmDialog(this,"El Código debe tener 5 caracteres.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                } else {                        
                try {
                    if (GestionDeAlmacen.existe(jTextField1.getText(),"Proveedores")) {
                       /*codigo para mostrar*/
                       ResultSet rs=GestionDeAlmacen.mostrar(jTextField1.getText(),"Proveedores");
                       String div=rs.getString("nif");
                       String divNum=div.substring(0,8);
                       String divLet=div.substring(8);
                       jTextField2.setText(divNum);
                       jTextField3.setText(divLet);
                       jTextField5.setText(rs.getString("apellidos"));
                       jTextField4.setText(rs.getString("nombre"));
                       jTextField6.setText(rs.getString("domicilio"));
                       jTextField7.setText(rs.getString("cp"));
                       jTextField8.setText(rs.getString("loaclidad"));
                       jTextField9.setText(rs.getString("telefono"));
                       jTextField10.setText(rs.getString("movil"));
                       jTextField11.setText(rs.getString("fax"));
                       jTextField12.setText(rs.getString("email"));
                       jTextField13.setText(rs.getString("total_compras"));
                       jButton1.setEnabled(true);
                       jButton2.setEnabled(true);
                       jButton3.setEnabled(true);
                    } else {
                         JOptionPane.showConfirmDialog(this,"Código Erróneo", "Código no existente. Imposible dar de baja este código.", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
                }
                } 
                    break;
                case 3:
                    if (jTextField1.getText().length()!=5) {
                    JOptionPane.showConfirmDialog(this,"El Código debe tener 5 caracteres.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                } else {
                try {
                    if (GestionDeAlmacen.existe(jTextField1.getText(),"Proveedores")) {
                       /*codigo para mostrar*/
                       ResultSet rs=GestionDeAlmacen.mostrar(jTextField1.getText(),"Proveedores");
                       jTextField1.setEnabled(false);
                       String div=rs.getString("nif");
                       String divNum=div.substring(0,8);
                       String divLet=div.substring(8);
                       jTextField2.setText(divNum);
                       jTextField3.setText(divLet);
                       jTextField5.setText(rs.getString("apellidos"));
                       jTextField4.setText(rs.getString("nombre"));
                       jTextField6.setText(rs.getString("domicilio"));
                       jTextField7.setText(rs.getString("cp"));
                       jTextField8.setText(rs.getString("loaclidad"));
                       jTextField9.setText(rs.getString("telefono"));
                       jTextField10.setText(rs.getString("movil"));
                       jTextField11.setText(rs.getString("fax"));
                       jTextField12.setText(rs.getString("email"));
                       jTextField13.setText(rs.getString("total_compras"));
                       actDesCasillas(1);
                    } else {
                         JOptionPane.showConfirmDialog(this,"Código Erróneo", "Código no existente.", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
                }
                    }
                    break;
                default:
                    JOptionPane.showConfirmDialog(this,"Error fatal.", "La apliación es irresoluble, llamar al tecnico.", JOptionPane.ERROR_MESSAGE);
                   
            }
            jTextField2.grabFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10){
            if (!jTextField2.getText().equals("") && jTextField2.getText().matches("[0-9]{8}")) {
                jTextField3.setText(String.valueOf(calcularLetra(Integer.valueOf(jTextField2.getText()))));
            }
            jTextField4.grabFocus();
                    }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().length()!=5) {
            JOptionPane.showConfirmDialog(this,"El Código debe tener 5 caracteres.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
        }else{
            if (!jTextField2.getText().matches("[0-9]{8}")) {
                JOptionPane.showConfirmDialog(this,"El NIF debe tener 8 números.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
            }else{
                if (!jTextField3.getText().matches("[A-Z]")) {
                    JOptionPane.showConfirmDialog(this,"El NIF debe tener una letra mayuscula.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                }else{
                    if (!jTextField4.getText().matches("([A-Za-z]+[ ]?)+")) {
                        JOptionPane.showConfirmDialog(this,"El Nombre no puede estar vacío, ni ser números.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                    }else{
                        if (!jTextField5.getText().matches("([A-Za-z]+[ ]?)+")) {
                            JOptionPane.showConfirmDialog(this,"Los Apellidos no pueden estar vacíos, ni ser números.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                        }else{
                            if (jTextField6.getText().equals("")) {
                                JOptionPane.showConfirmDialog(this,"La Dirección no puede estar vacía.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                            }else{
                                if (!jTextField7.getText().matches("[0-9]{5}")) {
                                    JOptionPane.showConfirmDialog(this,"El Código Postal(C.P.) debe tener 5 números.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                                }else{
                                    if (!jTextField8.getText().matches("([A-Za-z]+[ ]?)+")) {
                                        JOptionPane.showConfirmDialog(this,"La Localidad no puede estar vacía y no debe contener números.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                                    }else{
                                        if (!jTextField9.getText().equals("") && !jTextField9.getText().matches("[0-9]{9}")) {
                                            JOptionPane.showConfirmDialog(this,"El Teléfono debe tener 9 números.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                                        }else{
                                            if (!jTextField10.getText().equals("") && !jTextField10.getText().matches("[0-9]{9}")) {
                                                JOptionPane.showConfirmDialog(this,"El Móvil debe tener 9 números.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                                            }else{
                                                if (!jTextField11.getText().equals("") && !jTextField11.getText().matches("[0-9]{9}")) {
                                                    JOptionPane.showConfirmDialog(this,"El Fax debe tener 9 números.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                                                }else{
                                                    if (!jTextField12.getText().equals("") && !jTextField12.getText().matches("[A-Za-z]+[@][a-z]+.com")) {
                                                        JOptionPane.showConfirmDialog(this,"El e-mail no puede estar vacío y debe tener el siguiente formato:"
                                                            + "\n\"ejemplo@e-mail.com\"", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
                                                    }else{
                                                            switch(aux)
                                                            {
                                                                case 1:
                                                                    ArrayList <String> al=new ArrayList <String>();
                                                                    al.add(jTextField1.getText());
                                                                    al.add(jTextField2.getText()+jTextField3.getText());
                                                                    al.add(jTextField5.getText());
                                                                    al.add(jTextField4.getText());
                                                                    al.add(jTextField6.getText());
                                                                    al.add(jTextField7.getText());
                                                                    al.add(jTextField8.getText());
                                                                    al.add(jTextField9.getText());
                                                                    al.add(jTextField10.getText());
                                                                    al.add(jTextField11.getText());
                                                                    al.add(jTextField12.getText());
                                                                    al.add(jTextField13.getText());
                                                                    try {
                                                                        GestionDeAlmacen.altas(al, "Proveedores");
                                                                        JOptionPane.showConfirmDialog(this, "Alta realizada.", "Alta Cliente.",
                                                                        JOptionPane.CLOSED_OPTION);
                                                                        actDesCasillas(3);
                                                                    } catch (SQLException ex) {
                                                                        JOptionPane.showConfirmDialog(this,"Ocurrio un error al dar de alta al ciente, por favor intentelo de nuevo o reinicie la aplicación.", "Error en altas", JOptionPane.ERROR_MESSAGE);
                                                                        Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
                                                                    }
                                                                    break;
                                                                case 2:
                                                                    int res=JOptionPane.showConfirmDialog(this, "¿Esta seguro de dar de baja "
                                                                            + "al cliente con código"+jTextField1.getText()+"?", "Baja Cliente.",
                                                                    JOptionPane.YES_NO_CANCEL_OPTION);
                                                                    if (res==0) {
                                                                        try {
                                                                            GestionDeAlmacen.bajas(jTextField1.getText(), "Proveedores");
                                                                            JOptionPane.showConfirmDialog(this, "Baja realizada.", "Baja Cliente.",
                                                                            JOptionPane.CLOSED_OPTION);
                                                                            actDesCasillas(3);
                                                                        } catch (SQLException ex) {
                                                                            JOptionPane.showConfirmDialog(this,"Ocurrio un error al dar de baja al ciente, por favor intentelo de nuevo o reinicie la aplicación.", "Error en bajas", JOptionPane.ERROR_MESSAGE);
                                                                            Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
                                                                        }
                                                                    } else {
                                                                        ;
                                                                    }
                                                                    break;
                                                                case 3:
                                                                    int aux2=0;
                                                                    ResultSet rs=null;
                                                                    int res2=1;
                                                                    
                                                                    try {
                                                                        rs = GestionDeAlmacen.mostrar(jTextField1.getText(), "Proveedores");
                                                                        String div=rs.getString("nif");
                                                                        String divNum=div.substring(0,8);
                                                                        if (!divNum.equals(jTextField2.getText()) || !rs.getString("nombre").equals(jTextField4.getText()) || !rs.getString("apellidos").equals(jTextField5.getText()) || !rs.getString("domicilio").equals(jTextField6.getText()) || !rs.getString("cp").equals(jTextField7.getText()) || !rs.getString("loaclidad").equals(jTextField8.getText()) || !rs.getString("telefono").equals(jTextField9.getText()) || !rs.getString("movil").equals(jTextField10.getText()) || !rs.getString("fax").equals(jTextField11.getText()) || !rs.getString("email").equals(jTextField12.getText())) {
                                                                        res2=JOptionPane.showConfirmDialog(this, "¿Esta seguro que quieres modificar "
                                                                            + "al cliente con código"+jTextField1.getText()+"?", "Modificación Cliente.",
                                                                            JOptionPane.YES_NO_CANCEL_OPTION);
                                                                        }
                                                                    } catch (SQLException ex) {
                                                                        Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
                                                                    }
                                                                    
                                                                    if (res2==0) {
                                                                        try {
                                                                            
                                                                            String div=rs.getString("nif");
                                                                            String divNum=div.substring(0,8);
                                                                            if (!divNum.equals(jTextField2.getText())) {
                                                                                GestionDeAlmacen.modificaciones("nif", jTextField2.getText()+jTextField3.getText(), jTextField1.getText(), "Proveedores");
                                                                                aux2=1;
                                                                            }
                                                                            if (!rs.getString("nombre").equals(jTextField4.getText())) {
                                                                                GestionDeAlmacen.modificaciones("nombre", jTextField4.getText(), jTextField1.getText(), "Proveedores");
                                                                                aux2=1;
                                                                            }
                                                                            if (!rs.getString("apellidos").equals(jTextField5.getText())) {
                                                                                GestionDeAlmacen.modificaciones("apellidos", jTextField5.getText(), jTextField1.getText(), "Proveedores");
                                                                                aux2=1;
                                                                            }
                                                                            if (!rs.getString("domicilio").equals(jTextField6.getText())) {
                                                                                GestionDeAlmacen.modificaciones("domicilio", jTextField6.getText(), jTextField1.getText(), "Proveedores");
                                                                                aux2=1;
                                                                            }
                                                                            if (!rs.getString("cp").equals(jTextField7.getText())) {
                                                                                GestionDeAlmacen.modificaciones("cp", jTextField7.getText(), jTextField1.getText(), "Proveedores");
                                                                                aux2=1;
                                                                            }
                                                                            if (!rs.getString("loaclidad").equals(jTextField8.getText())) {
                                                                                GestionDeAlmacen.modificaciones("loaclidad", jTextField8.getText(), jTextField1.getText(), "Proveedores");
                                                                                aux2=1;
                                                                            }
                                                                            if (!rs.getString("telefono").equals(jTextField9.getText())) {
                                                                                GestionDeAlmacen.modificaciones("telefono", jTextField9.getText(), jTextField1.getText(), "Proveedores");
                                                                                aux2=1;
                                                                            }
                                                                            if (!rs.getString("movil").equals(jTextField10.getText())) {
                                                                                GestionDeAlmacen.modificaciones("movil", jTextField10.getText(), jTextField1.getText(), "Proveedores");
                                                                                aux2=1;
                                                                            }
                                                                            if (!rs.getString("fax").equals(jTextField11.getText())) {
                                                                                GestionDeAlmacen.modificaciones("fax", jTextField11.getText(), jTextField1.getText(), "Proveedores");
                                                                                aux2=1;
                                                                            }
                                                                            if (!rs.getString("email").equals(jTextField12.getText())) {
                                                                                GestionDeAlmacen.modificaciones("email", jTextField12.getText(), jTextField1.getText(), "Proveedores");
                                                                                aux2=1;
                                                                            }
                                                                            
                                                                            JOptionPane.showConfirmDialog(this, "Modificación realizada.", "Modificación Cliente.",
                                                                            JOptionPane.CLOSED_OPTION);
                                                                            actDesCasillas(3);
                                                                        } catch (SQLException ex) {
                                                                            JOptionPane.showConfirmDialog(this,"Ocurrio un error al modificar al ciente, por favor intentelo de nuevo o reinicie la aplicación.", "Error en modificación", JOptionPane.ERROR_MESSAGE);
                                                                            Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
                                                                        }
                                                                    } else {
                                                                        ;
                                                                    }
                                                                    break;
                                                                default:
                                                                    JOptionPane.showConfirmDialog(this,"Error fatal.", "La apliación es irresoluble, llamar al tecnico.", JOptionPane.ERROR_MESSAGE);

                                                            }
                                                        
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField4.grabFocus();
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField1.grabFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField5.grabFocus();
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField7.grabFocus();
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField8.grabFocus();
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField6.grabFocus();
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField9.grabFocus();
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField10.grabFocus();
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField11.grabFocus();
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField12.grabFocus();
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) jTextField13.grabFocus();
    }//GEN-LAST:event_jTextField12KeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEnabled(true);
        jScrollPane2.setVisible(false);
        jPanel1.setVisible(false);
        this.setBounds(0, 0, 487, 450);
        aux=1;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEnabled(true);
        jScrollPane2.setVisible(false);
        jPanel1.setVisible(false);
        this.setBounds(0, 0, 487, 450);
        aux=2;
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEnabled(true);
        jScrollPane2.setVisible(false);
        jPanel1.setVisible(false);
        this.setBounds(0, 0, 487, 450);
        aux=3;
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        padre.setEnabled(true);
        padre.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        actDesCasillas(2);
        this.setBounds(0, 0, 487, 450);
        jScrollPane2.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        mostrarApellido();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        mostrarGraficos();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        mostrarCodigo();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        mostrarPorUnicoCodigo();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        mostrarEntreCodigo();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores(padre).setVisible(true);
            }
        });

    }
    protected void processWindowEvent(java.awt.event.WindowEvent e) {/*Este metodo debemos añadirlo completo a mano,
     con el habilitamos de nuevo la primera ventana.*/
        super.processWindowEvent(e);
        if (e.getID() == java.awt.event.WindowEvent.WINDOW_CLOSING) {
        padre.setEnabled(true);
        padre.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    static char calcularLetra(int dni) {
        String caracteres = "TRWAGMYFPDXBNJZSQVHLCKE";
        int resto = dni % 23;
        return caracteres.charAt(resto);
    }
    
    private void actDesCasillas(int i) {
       switch(i)
            {
                case 1:
                    jTextField2.setEnabled(true);
                    jTextField4.setEnabled(true);
                    jTextField5.setEnabled(true);
                    jTextField6.setEnabled(true);
                    jTextField7.setEnabled(true);
                    jTextField8.setEnabled(true);
                    jTextField9.setEnabled(true);
                    jTextField10.setEnabled(true);
                    jTextField11.setEnabled(true);
                    jTextField12.setEnabled(true);
                    jButton1.setEnabled(true);
                    jButton2.setEnabled(true);
                    jButton3.setEnabled(true);
                    break;
                case 2:
                    jTextField1.setEnabled(false);
                    jTextField2.setEnabled(false);
                    jTextField4.setEnabled(false);
                    jTextField5.setEnabled(false);
                    jTextField6.setEnabled(false);
                    jTextField7.setEnabled(false);
                    jTextField8.setEnabled(false);
                    jTextField9.setEnabled(false);
                    jTextField10.setEnabled(false);
                    jTextField11.setEnabled(false);
                    jTextField12.setEnabled(false);
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                    jButton3.setEnabled(false);
                    break;
                case 3:
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    jTextField10.setText("");
                    jTextField11.setText("");
                    jTextField12.setText("");
                    jTextField13.setText("");
                    jTextField1.setEnabled(true);
                    jTextField2.setEnabled(false);
                    jTextField4.setEnabled(false);
                    jTextField5.setEnabled(false);
                    jTextField6.setEnabled(false);
                    jTextField7.setEnabled(false);
                    jTextField8.setEnabled(false);
                    jTextField9.setEnabled(false);
                    jTextField10.setEnabled(false);
                    jTextField11.setEnabled(false);
                    jTextField12.setEnabled(false);
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                    jButton3.setEnabled(false);
                    jTextField1.grabFocus();
                    break;
                default:
                    
            }
        
    }

    private void mostrarApellido() {
        /* La siguiente línea se utiliza para descargar el contenido del objeto de
        la memoria. De esta forma, si se pulsa varias veces este botón, el objeto
        es refrescado.
        */
        jScrollPane2.setVisible(false);
        jPanel1.setVisible(false);
        DefaultTableModel modelo = new DefaultTableModel();
        JTable jTable2 = new JTable(modelo){
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
        };
        modelo.addColumn("Código");
        modelo.addColumn("NIF");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Domicilio");
        modelo.addColumn("Código Postal");
        modelo.addColumn("Localidad");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Móvil");
        modelo.addColumn("Fax");
        modelo.addColumn("E-mail");
        modelo.addColumn("Total Compras");
        try {
            ResultSet rs=GestionDeAlmacen.mostrarEspec("SELECT * from Proveedores Order by apellidos");
            while (rs.next()) {                
                Object [] fila = new Object[12];
                fila[0] = rs.getString("codigo");
                fila[1] = rs.getString("nif");
                fila[2] = rs.getString("nombre");
                fila[3] = rs.getString("apellidos");
                fila[4] = rs.getString("domicilio");
                fila[5] = rs.getString("cp");
                fila[6] = rs.getString("loaclidad");
                fila[7] = rs.getString("telefono");
                fila[8] = rs.getString("movil");
                fila[9] = rs.getString("fax");
                fila[10] = rs.getString("email");
                fila[11] = rs.getString("total_compras");
                modelo.addRow ( fila );
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
         // Añade una fila al final
       /*
        
        // En las siguientes líneas se deshabilita la edición del objeto JTable.
        jTable2=new JTable(vArticulos,vTitColum) {
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
         // Añade una fila al final
       /*
        
        // En las siguientes líneas se deshabilita la edición del objeto JTable.
        jTable2=new JTable(vArticulos,vTitColum) {
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
        };*/

        /* El método setSelectionMode recibe un entero que define el tipo
        de selección:

        0 -> Sólo se puede seleccionar una fila.
        1 -> Se pueden seleccionar múltiples filas consecutivas.
        2 -> Se pueden seleccionar múltiples filas aunque no sean
        consecutivas.

        */

        jTable2.setSelectionMode(0);
        jScrollPane2=new JScrollPane(jTable2);
        jTable2.setBounds(0, 0, 459, 219);
        jScrollPane2.setBounds(4, 365, 459, 219);
        this.setBounds(0, 0, 487, 750);
        getContentPane().add(jScrollPane2,null);
        jScrollPane2.setVisible(true);

        /* En las siguientes líneas se activa el método mouseClicked del objeto JTable
        para visualizar los datos del registro seleccionado en el formulario superior.
        */
        
    }

    private void mostrarGraficos() {
        jPanel1.setVisible(false);
        jScrollPane2.setVisible(false);
        try {
            ResultSet rs=GestionDeAlmacen.mostrarEspec("SELECT cp, count(loaclidad) c FROM Proveedores GROUP BY cp");
            DefaultPieDataset dataset = new DefaultPieDataset();
            while (rs.next()) {
                dataset.setValue(rs.getString("cp"), Integer.parseInt(rs.getString("c")));
            }
           
            JFreeChart fc = ChartFactory.createPieChart("Grafico de localidad", dataset, true, true, false);
            ChartPanel cp = new ChartPanel(fc);//creamos un panel con la tabla dentro
            jPanel1.add(cp);
            cp.setBounds(0, 0, 459, 259);
            this.setBounds(0, 0, 487, 750);
            jPanel1.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void mostrarCodigo() {
        /* La siguiente línea se utiliza para descargar el contenido del objeto de
        la memoria. De esta forma, si se pulsa varias veces este botón, el objeto
        es refrescado.
        */
        jScrollPane2.setVisible(false);
        jPanel1.setVisible(false);
        DefaultTableModel modelo = new DefaultTableModel();
        JTable jTable2 = new JTable(modelo){
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
        };
        modelo.addColumn("Código");
        modelo.addColumn("NIF");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Domicilio");
        modelo.addColumn("Código Postal");
        modelo.addColumn("Localidad");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Móvil");
        modelo.addColumn("Fax");
        modelo.addColumn("E-mail");
        modelo.addColumn("Total Compras");
        try {
            ResultSet rs=GestionDeAlmacen.mostrarEspec("SELECT * from Proveedores Order by codigo");
            while (rs.next()) {                
                Object [] fila = new Object[12];
                fila[0] = rs.getString("codigo");
                fila[1] = rs.getString("nif");
                fila[2] = rs.getString("nombre");
                fila[3] = rs.getString("apellidos");
                fila[4] = rs.getString("domicilio");
                fila[5] = rs.getString("cp");
                fila[6] = rs.getString("loaclidad");
                fila[7] = rs.getString("telefono");
                fila[8] = rs.getString("movil");
                fila[9] = rs.getString("fax");
                fila[10] = rs.getString("email");
                fila[11] = rs.getString("total_compras");
                modelo.addRow ( fila );
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
         // Añade una fila al final
       /*
        
        // En las siguientes líneas se deshabilita la edición del objeto JTable.
        jTable2=new JTable(vArticulos,vTitColum) {
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
         // Añade una fila al final
       /*
        
        // En las siguientes líneas se deshabilita la edición del objeto JTable.
        jTable2=new JTable(vArticulos,vTitColum) {
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
        };*/

        /* El método setSelectionMode recibe un entero que define el tipo
        de selección:

        0 -> Sólo se puede seleccionar una fila.
        1 -> Se pueden seleccionar múltiples filas consecutivas.
        2 -> Se pueden seleccionar múltiples filas aunque no sean
        consecutivas.

        */

        jTable2.setSelectionMode(0);
        jScrollPane2=new JScrollPane(jTable2);
        jTable2.setBounds(0, 0, 459, 219);
        jScrollPane2.setBounds(new Rectangle(4, 365, 459, 219));
        this.setBounds(0, 0, 487, 750);
        getContentPane().add(jScrollPane2,null);
        jScrollPane2.setVisible(true);

        /* En las siguientes líneas se activa el método mouseClicked del objeto JTable
        para visualizar los datos del registro seleccionado en el formulario superior.
        */
        
    
        
    }

    private void mostrarPorUnicoCodigo() {
        /* La siguiente línea se utiliza para descargar el contenido del objeto de
        la memoria. De esta forma, si se pulsa varias veces este botón, el objeto
        es refrescado.
        */
        jScrollPane2.setVisible(false);
        jPanel1.setVisible(false);
        String st=JOptionPane.showInputDialog("Introduce el código.");
        if (!st.matches("[a-zA-Z_0-9]{5}")) {
            JOptionPane.showConfirmDialog(this,"Para realizar una consulta por un código especifico, "
                    + "\ndebe rellenar el campo un código de 5 caracteres.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
        } else {
            try{
            if (GestionDeAlmacen.existe(st, "Proveedores")) {
        
        DefaultTableModel modelo = new DefaultTableModel();
        JTable jTable2 = new JTable(modelo){
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
        };
        modelo.addColumn("Código");
        modelo.addColumn("NIF");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Domicilio");
        modelo.addColumn("Código Postal");
        modelo.addColumn("Localidad");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Móvil");
        modelo.addColumn("Fax");
        modelo.addColumn("E-mail");
        modelo.addColumn("Total Compras");
        try {
            ResultSet rs=GestionDeAlmacen.mostrar(st,"Proveedores");
                 
                Object [] fila = new Object[12];
                fila[0] = rs.getString("codigo");
                fila[1] = rs.getString("nif");
                fila[2] = rs.getString("nombre");
                fila[3] = rs.getString("apellidos");
                fila[4] = rs.getString("domicilio");
                fila[5] = rs.getString("cp");
                fila[6] = rs.getString("loaclidad");
                fila[7] = rs.getString("telefono");
                fila[8] = rs.getString("movil");
                fila[9] = rs.getString("fax");
                fila[10] = rs.getString("email");
                fila[11] = rs.getString("total_compras");
                modelo.addRow ( fila );
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
         // Añade una fila al final
       /*
        
        // En las siguientes líneas se deshabilita la edición del objeto JTable.
        jTable2=new JTable(vArticulos,vTitColum) {
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
         // Añade una fila al final
       /*
        
        // En las siguientes líneas se deshabilita la edición del objeto JTable.
        jTable2=new JTable(vArticulos,vTitColum) {
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
        };*/

        /* El método setSelectionMode recibe un entero que define el tipo
        de selección:

        0 -> Sólo se puede seleccionar una fila.
        1 -> Se pueden seleccionar múltiples filas consecutivas.
        2 -> Se pueden seleccionar múltiples filas aunque no sean
        consecutivas.

        */

        jTable2.setSelectionMode(0);
        jScrollPane2=new JScrollPane(jTable2);
        jTable2.setBounds(0, 0, 459, 219);
        jScrollPane2.setBounds(new Rectangle(4, 365, 459, 219));
        this.setBounds(0, 0, 487, 750);
        getContentPane().add(jScrollPane2,null);
        jScrollPane2.setVisible(true);

        /* En las siguientes líneas se activa el método mouseClicked del objeto JTable
        para visualizar los datos del registro seleccionado en el formulario superior.
        */
        
        } else {
                JOptionPane.showConfirmDialog(this,"Los codigos introducidos no son correctos, no existen.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
            }
            }catch (SQLException e){
            
            }
        }
    }

    private void mostrarEntreCodigo() {
        /* La siguiente línea se utiliza para descargar el contenido del objeto de
        la memoria. De esta forma, si se pulsa varias veces este botón, el objeto
        es refrescado.
        */
        jScrollPane2.setVisible(false);
        jPanel1.setVisible(false);
        String st=JOptionPane.showInputDialog("Introduce los dos codigos separados por un espacio.");
        if (!st.matches("[a-zA-Z_0-9]{5} [a-zA-Z_0-9]{5}")) {
            JOptionPane.showConfirmDialog(this,"Para realizar una consulta entre códigos, debe rellenar el campo con los dos codigos separados por un espacio en blanco.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
        } else {
            String [] cods=st.split(" ");
            try{
            if (GestionDeAlmacen.existe(cods[0], "Proveedores") && GestionDeAlmacen.existe(cods[1], "Proveedores")) {
                DefaultTableModel modelo = new DefaultTableModel();
        JTable jTable2 = new JTable(modelo){
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
        };
        modelo.addColumn("Código");
        modelo.addColumn("NIF");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Domicilio");
        modelo.addColumn("Código Postal");
        modelo.addColumn("Localidad");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Móvil");
        modelo.addColumn("Fax");
        modelo.addColumn("E-mail");
        modelo.addColumn("Total Compras");
        try {
            ResultSet rs=GestionDeAlmacen.mostrarEspec("SELECT * from Proveedores WHERE cast(codigo as integer) >=" + Integer.valueOf(cods[0]) + "AND  cast(codigo as integer)  <=" + Integer.valueOf(cods[1]) + " order by codigo");
            while (rs.next()){               
                        Object [] fila = new Object[12];
                        fila[0] = rs.getString("codigo");
                        fila[1] = rs.getString("nif");
                        fila[2] = rs.getString("nombre");
                        fila[3] = rs.getString("apellidos");
                        fila[4] = rs.getString("domicilio");
                        fila[5] = rs.getString("cp");
                        fila[6] = rs.getString("loaclidad");
                        fila[7] = rs.getString("telefono");
                        fila[8] = rs.getString("movil");
                        fila[9] = rs.getString("fax");
                        fila[10] = rs.getString("email");
                        fila[11] = rs.getString("total_compras");
                        modelo.addRow ( fila );
            }
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
         // Añade una fila al final
       /*
        
        // En las siguientes líneas se deshabilita la edición del objeto JTable.
        jTable2=new JTable(vArticulos,vTitColum) {
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
         // Añade una fila al final
       /*
        
        // En las siguientes líneas se deshabilita la edición del objeto JTable.
        jTable2=new JTable(vArticulos,vTitColum) {
        @Override
        public boolean isCellEditable(int row, int column) {
        return false;
        }
        };*/

        /* El método setSelectionMode recibe un entero que define el tipo
        de selección:

        0 -> Sólo se puede seleccionar una fila.
        1 -> Se pueden seleccionar múltiples filas consecutivas.
        2 -> Se pueden seleccionar múltiples filas aunque no sean
        consecutivas.

        */

        jTable2.setSelectionMode(0);
        jScrollPane2=new JScrollPane(jTable2);
        jTable2.setBounds(0, 0, 459, 219);
        jScrollPane2.setBounds(new Rectangle(4, 365, 459, 219));
        this.setBounds(0, 0, 487, 750);
        getContentPane().add(jScrollPane2,null);
        jScrollPane2.setVisible(true);

        /* En las siguientes líneas se activa el método mouseClicked del objeto JTable
        para visualizar los datos del registro seleccionado en el formulario superior.
        */
            } else {
                JOptionPane.showConfirmDialog(this,"Los codigos introducidos no son correctos, no existen.", "Gestión de proveedores", JOptionPane.ERROR_MESSAGE);
            }
            }catch (SQLException e){
            
            }
                    }
        
        
    
        
    }
}
